export const mockCharacters = [
  {
    "id": 1,
    "name": "Luke Skywalker",
    "height": 172,
    "mass": 77,
    "hairColor": "blond",
    "skinColor": "fair",
    "eyeColor": "blue",
    "birthEear": "19BBY",
    "gender": "male",
    "image": "https://starwars-visualguide.com/assets/img/characters/1.jpg"
  },
  {
    "id": 2,
    "name": "C-3PO",
    "height": 167,
    "mass": 75,
    "hairColor": "n/a",
    "skinColor": "gold",
    "eyeColor": "yellow",
    "birthYear": "112BBY",
    "gender": "n/a",
    "image": "https://starwars-visualguide.com/assets/img/characters/2.jpg"
  },
  {
    "id": 3,
    "name": "R2-D2",
    "height": 96,
    "mass": 32,
    "hairColor": "n/a",
    "skinColor": "white, blue",
    "eyeColor": "red",
    "birthYear": "33BBY",
    "gender": "n/a",
    "image": "https://starwars-visualguide.com/assets/img/characters/3.jpg"
  },
  {
    "id": 4,
    "name": "Darth Vader",
    "height": 202,
    "mass": 136,
    "hairColor": "none",
    "skinColor": "white",
    "eyeColor": "yellow",
    "birthYear": "41.9BBY",
    "gender": "male",
    "image": "https://starwars-visualguide.com/assets/img/characters/4.jpg"
  },
  {
    "id": 5,
    "name": "Leia Organa",
    "height": 150,
    "mass": 49,
    "hairColor": "brown",
    "skinColor": "light",
    "eyeColor": "brown",
    "birthYear": "19BBY",
    "gender": "female",
    "image": "https://starwars-visualguide.com/assets/img/characters/5.jpg"
  },
  {
    "id": 6,
    "name": "Owen Lars",
    "height": 178,
    "mass": 120,
    "hairColor": "brown, grey",
    "skinColor": "light",
    "eyeColor": "blue",
    "birthYear": "52BBY",
    "gender": "male",
    "image": "https://starwars-visualguide.com/assets/img/characters/6.jpg"
  },
  {
    "id": 7,
    "name": "Beru Whitesun lars",
    "height": 165,
    "mass": 75,
    "hairColor": "brown",
    "skinColor": "light",
    "eyeColor": "blue",
    "birthYear": "47BBY",
    "gender": "female",
    "image": "https://starwars-visualguide.com/assets/img/characters/7.jpg"
  },
  {
    "id": 8,
    "name": "R5-D4",
    "height": 97,
    "mass": 32,
    "hairColor": "n/a",
    "skinColor": "white, red",
    "eyeColor": "red",
    "birthYear": "unknown",
    "gender": "n/a",
    "image": "https://starwars-visualguide.com/assets/img/characters/8.jpg"
  },
  {
    "id": 9,
    "name": "Biggs Darklighter",
    "height": 183,
    "mass": 84,
    "hairColor": "black",
    "skinColor": "light",
    "eyeColor": "brown",
    "birthYear": "24BBY",
    "gender": "male",
    "image": "https://starwars-visualguide.com/assets/img/characters/9.jpg"
  },
  {
    "id": 10,
    "name": "Obi-Wan Kenobi",
    "height": 182,
    "mass": 77,
    "hairColor": "auburn, white",
    "skinColor": "fair",
    "eyeColor": "blue-gray",
    "birthYear": "57BBY",
    "gender": "male",
    "image": "https://starwars-visualguide.com/assets/img/characters/10.jpg"
  }
];